spring:
 profiles:
  active: dev
 http:
  encoding:
   force: true
 datasource:    
   driver-class-name: com.mysql.jdbc.Driver    
   url: jdbc:mysql://localhost:3306/springboot    
   username: root    
   password: root
 application:
  #注意这里是作为服务注册名称，在eureka注册中心注册这个名称，自动转化为全大写，之后调用服务用服务名调用
  name: user-service 
 freemarker:
  prefer-file-system-access: false
eureka:
  instance:
    hostname: localhost
  client:
    ## 是否注册自身到eureka服务器,因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    register-with-eureka: true
    ## 是否从eureka服务器获取注册信息，所以这里是false
    fetch-registry: true 
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
mybatis:
 mapper-locations: classpath:mybatis/mapper/*.xml
 config-location: classpath:mybatis/mybatis-config.xml
 
 